#### DQN HYPERPARAMETERS AND GLOBALS ####

# Q-learning settings
LEARNING_RATE = 0.00005
DISCOUNT_FACTOR = 0.9999
EPOCHS = 50
LEARNING_STEPS_PER_EPOCH = 250
REPLAY_MEMORY_SIZE = 1000

EPS_DECAY_10 = 0.25
EPS_DECAY_60 = 0.7

# EPS_DECAY_10 = 0.1
# EPS_DECAY_60 = 0.6

# NN learning settings
#BATCH_SIZE = 150
#SENTANCE_LEN = 100
WORD_EMBEDDING_LEN = 50
CONV_KERNEL_LEN = 4
RESOLUTION = (SENTANCE_LEN,WORD_EMBEDDING_LEN)
#HIDDEN_UNITS = 64
#FILTER_COUNT = 32

# Training regime
TEST_EPISODES_PER_EPOCH = 10

# Other parameters
#FRAME_REPEAT = 4
EPISODES_TO_WATCH = 15


SAVE_MODEL = True
LOAD_MODEL = False
#SKIP_TEST = False

#PRINT_TRAINING_PROCESS = False

